gripper: {
  gripper_type: 'yale_openhand_O'
}
model_O: {
  proximal_finger_spring_coefficient: 7, # 7
  distal_finger_spring_coefficient: 14, # 14
  proximal_finger_damping_coefficient: 6.0,
  distal_finger_damping_coefficient: 6.0,
  tendon_max_force: 20, # 20
  finger_tendon_force_distribution: [1,0.5],
  lift_values: [0,0.2],
}
